spring.application.name=estude-noah-backend
server.address=0.0.0.0
server.port=${PORT:8080}
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
spring.servlet.multipart.max-file-size=${MAX_UPLOAD_SIZE:50MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:51MB}
